# 作業目標:

    使用CIFAR100, 數據集變大的影響
    
    
# 作業重點:¶

   了解 CIFAR100 跟 CIFAR10 數據及差異


In [21]:
import numpy
from tensorflow.keras.datasets import cifar100
from tensorflow.keras.utils import to_categorical
import numpy as np
np.random.seed(100)

# 資料準備

In [22]:
cifar100 = cifar100.load_data()
(x_train, y_train), (x_test, y_test) = cifar100

# Image normalize 

In [24]:
x_train = x_train / 255.0
x_test = x_test / 255.0
print(x_train)
print("=====")
print(x_test)

[[[[1.         1.         1.        ]
   [1.         1.         1.        ]
   [1.         1.         1.        ]
   ...
   [0.76470588 0.80392157 0.75686275]
   [0.83137255 0.87843137 0.8       ]
   [0.71372549 0.76078431 0.65490196]]

  [[1.         1.         1.        ]
   [0.99607843 0.99607843 0.99607843]
   [0.99607843 0.99607843 0.99607843]
   ...
   [0.66666667 0.69019608 0.58823529]
   [0.63137255 0.65882353 0.50980392]
   [0.57254902 0.60392157 0.44313725]]

  [[1.         1.         1.        ]
   [0.99607843 0.99607843 0.99607843]
   [1.         1.         1.        ]
   ...
   [0.74117647 0.78039216 0.6627451 ]
   [0.65098039 0.69803922 0.50980392]
   [0.4745098  0.52156863 0.34117647]]

  ...

  [[0.58039216 0.7254902  0.30980392]
   [0.55686275 0.71372549 0.22352941]
   [0.54901961 0.70196078 0.23529412]
   ...
   [0.11764706 0.06666667 0.00392157]
   [0.25490196 0.24313725 0.05882353]
   [0.29803922 0.30196078 0.07843137]]

  [[0.47843137 0.61568627 0.25882353]
   [0.4

# 轉換label 為OneHot Encoding

In [25]:
y_train =  to_categorical(y_train)
y_test = to_categorical(y_test)
print(f'''
{y_train}
=====
{y_test}
''')


[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
=====
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]

